### ISSUE TITLE
Unit test failures

### ISSUE THREAD

**Issue by koenderks** [jasp-stats/jaspBain#29]
Unit tests currently fail, I cannot reproduce this on Windows.

**Comment by koenderks** [comment]
@TimKDJ Any ideas about this?

**Comment by TimKDJ** [comment]
Do they still work perfectly if you
1. Restart R
2. Replace your regular, personal package library in `.libPaths()` with a new, empty folder
3. Reinstall the `jaspBain` package with its dependencies to the new empty folder
4. And then run the unit tests
