### ISSUE TITLE
No capitalisation for bain

### ISSUE THREAD

**Issue by AlexanderLyNL** [jasp-stats/jaspBain#49]
I f I remember correctly, it's now called bain all in small cases. The results and interface still show Bain. Not sure if I'm correct or not.

**Comment by koenderks** [comment]
Does not capitalizing Bain not interfere with the JASP style? Every other module / table / plot name is also capitalized if I remember correctly?

**Comment by EJWagenmakers** [comment]
Unless Herbert complains we can leave this as is.
