### ISSUE TITLE
"bain" or "Bain"

### ISSUE THREAD

**Issue by amirmasoudabdol** [jasp-stats/jaspBain#74]
While testing the changes to the help files, I noticed that most Bain's help files have headers like, "bain ANOVA", and "bain Welch Test", etc. It's odd that they are not uppercased, especially in the title. Even if the abbreviation or the name of the package is lowercased, I feel it should appear as uppercase in the title.

**Comment by koenderks** [comment]
Agreed. i’ll make the changes.

**Comment by amirmasoudabdol** [comment]
Thanks! 🙏🏼

P.S. Feel free to add it to the 0.16.1 if you want.
